# Generated by Django 3.0.5 on 2020-04-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='category',
            field=models.CharField(choices=[('R', 'Residential'), ('C', 'Commercial')], default='R', max_length=1),
            preserve_default=False,
        ),
    ]
