# Generated by Django 3.0.5 on 2020-04-12 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
    ]
